export const GET_STATE_DATA = "GET_STATE_DATA";
export const GET_LATEST_TIMESTAMP = "GET_LATEST_TIMESTAMP";
export const SET_LOADING = "SET_LOADING";
export const GET_ZONE_INFO = "GET_ZONE_INFO";
export const FILTER_DISTRICTS = "FILTER_DISTRICTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const TIME_SERIES = "TIME_SERIES";
export const DARK_MODE = "DARK_MODE";
